require "minitest/rails/shoulda/version"
require "minitest/rails/shoulda/assertions"
require "minitest/rails/shoulda/expectations"
require "minitest/rails/shoulda/dsl"
require "minitest/rails/shoulda/matchers"
